export const  FETCHING_DATA = 'FETCHING_DATA';
export const  FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS';
export const  FETCHING_DATA_ERROR = 'FETCHING_DATA_ERROR';

// CONSTANTS POST SEND USER DATA TO SERVER

export const  FETCHING_POST_USER_DATA = 'FETCHING_POST_USER_DATA';
export const  FETCHING_POST_USER_DATA_SUCCESS = 'FETCHING_POST_USER_DATA_SUCCESS';
export const  FETCHING_POST_USER_DATA_ERROR = 'FETCHING_POST_USER_DATA_ERROR';
export const  ADD_POST_USER_DATA_ERROR = 'ADD_POST_USER_DATA_ERROR';


// CONSTANTS DISPATCH COORDINATES

export const  FETCHING_COORDINATES_DATA = 'FETCHING_COORDINATES_DATA';
export const  FETCHING_COORDINATES_DATA_SUCCESS = 'FETCHING_COORDINATES_DATA_SUCCESS';
export const  FETCHING_COORDINATES_DATA_ERROR = 'FETCHING_COORDINATES_DATA_ERROR';

// CONSTANTS DISPATCH CITIES

export const  FETCHING_CITIES_DATA = 'FETCHING_CITIES_DATA';
export const  FETCHING_CITIES_DATA_SUCCESS = 'FETCHING_CITIES_DATA_SUCCESS';
export const  FETCHING_CITIES_DATA_ERROR = 'FETCHING_CITIES_DATA_ERROR';


